In [122]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [154]:
df = pd.DataFrame([[1,3,5],[1,2,3],[4,4,4],[5,5,5]], columns=['s1','s2','s3'])

In [155]:
df

s1  s2  s3
0   1   3   5
1   1   2   3
2   4   4   4
3   5   5   5

In [156]:
df.transpose()

0  1  2  3
s1  1  1  4  5
s2  3  2  4  5
s3  5  3  4  5

In [158]:
pca = PCA()
pca.fit_transform(df.transpose())

array([[ -2.23606798e+00,   1.13483031e-17,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.23606798e+00,   1.13483031e-17,   0.00000000e+00]])

In [141]:
scaled_pca_data = pca.fit_transform(scale(df.transpose()))
scaled_pca_data

array([[-1.73205081],
       [ 0.        ],
       [ 1.73205081]])

In [159]:
scale(df.transpose())

array([[-1.22474487, -1.22474487,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  0.        ,  0.        ]])

In [163]:
df2 = pd.DataFrame()
df2.append({'foo':1, 'bar':2}, ignore_index=True)

bar  foo
0  2.0  1.0