In [104]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [91]:
df = pd.DataFrame([[1,2,3],[1,2,3]], columns=['s1','s2','s3'])

In [92]:
df

s1  s2  s3
0   1   2   3
1   1   2   3

In [93]:
df.transpose()

0  1
s1  1  1
s2  2  2
s3  3  3

In [105]:
scale(df.transpose())

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

In [108]:
pca = PCA(n_components=1)
pca_data = pca.fit_transform(df.transpose())
pca_data

array([[-1.41421356],
       [ 0.        ],
       [ 1.41421356]])

In [109]:
scaled_pca_data = pca.fit_transform(scale(df.transpose()))
scaled_pca_data

array([[-1.73205081],
       [ 0.        ],
       [ 1.73205081]])

In [ ]:
df2 = pd.DataFrame([[1,2,3],[1,2,3]], columns=['s1','s2','s3'])