In [1]:
import numpy as np

In [2]:
a = [[1,2,3],
     [4,5,6]]

b = [[7,8],
     [9,10],
     [11,12]]

np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [3]:
np.dot(2,[[4,0],[1,-9]])

array([[  8,   0],
       [  2, -18]])

In [24]:
# a_ndarray = np.ndarray(shape=(2,3), buffer=np.a)
a_array = np.array(a)
b_array = np.array(b)
a_array.dot(b_array)

array([[ 58,  64],
       [139, 154]])

In [28]:
c_array = np.array(2)
c_array

array(2)

In [29]:
a_array.dot(b_array).dot(c_array)

array([[116, 128],
       [278, 308]])

In [32]:
a_array.dot(2)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
e = np.array([[1,2,3],
              [4,5,6]])
f = np.array([[1,1,1],
              [1,1,1]])
e+f

array([[2, 3, 4],
       [5, 6, 7]])