In [1]:
import numpy as np

In [48]:
alpha = np.array(0.5)
F_0 = np.array([1, 0, 0, 0, 0, 1])
A = np.array([[0, 1/2, 0, 1/2, 0, 0],
             [1/2, 0, 0, 1/2, 0, 0],
             [0, 0, 0, 0, 1/2, 1/2],
             [1/3, 1/3, 0, 0, 0, 1/3],
             [0, 0, 1/2, 0, 0, 1/2],
             [0, 0, 1/3, 1/3, 1/3, 0]])
F_t = F_0.copy()

In [39]:
def get_next_F_t(current_F, initial_F, A, alpha, decimals):
    next_F_t = alpha.dot(current_F).dot(A) + (1 - alpha) * initial_F
    next_F_t = np.around(next_F_t, decimals = decimals)
    return next_F_t

In [40]:
print(F_t)
for _ in range(20):
    F_t = get_next_F_t(F_t, F_0, A, alpha, 3)
    print(F_t)

[1 0 0 0 0 1]
[ 0.5    0.25   0.167  0.417  0.167  0.5  ]
[ 0.632  0.194  0.125  0.271  0.125  0.653]
[ 0.594  0.203  0.14   0.315  0.14   0.608]
[ 0.603  0.201  0.136  0.301  0.136  0.622]
[ 0.6    0.201  0.138  0.305  0.138  0.618]
[ 0.601  0.201  0.137  0.303  0.137  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.619]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]
[ 0.601  0.201  0.138  0.304  0.138  0.62 ]


In [42]:
print(F_t)
for _ in range(20):
    F_t = get_next_F_t(F_t, F_0, A, alpha, 4)
    print(F_t)

[1 0 0 0 0 1]
[ 0.5     0.25    0.1667  0.4167  0.1667  0.5   ]
[ 0.632   0.1945  0.125   0.2708  0.125   0.6528]
[ 0.5938  0.2031  0.14    0.3154  0.14    0.6076]
[ 0.6033  0.201   0.1363  0.3005  0.1363  0.6226]
[ 0.6003  0.2009  0.1378  0.3048  0.1378  0.6182]
[ 0.601   0.2009  0.1375  0.3033  0.1375  0.6197]
[ 0.6008  0.2008  0.1377  0.3038  0.1377  0.6193]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6195]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.1376  0.6194]
[ 0.6008  0.2008  0.1376  0.3036  0.

In [49]:
print(F_t)
for _ in range(20):
    F_t = get_next_F_t(F_t, F_0, A, alpha, 10)
    print(F_t)

[1 0 0 0 0 1]
[ 0.5         0.25        0.16666667  0.41666667  0.16666667  0.5       ]
[ 0.63194444  0.19444444  0.125       0.27083333  0.125       0.65277778]
[ 0.59375     0.203125    0.1400463   0.31539352  0.1400463   0.60763889]
[ 0.60334684  0.20100309  0.13628472  0.3004919   0.13628472  0.62258873]
[ 0.60033275  0.20091869  0.13783597  0.30485227  0.13783597  0.61822434]
[ 0.60103838  0.2008919   0.13749638  0.30335025  0.13749638  0.6197267 ]
[ 0.60078135  0.20081797  0.13766188  0.30377035  0.13766188  0.61930657]
[ 0.60083289  0.20082373  0.13763323  0.30361759  0.13763323  0.61945933]
[ 0.60080886  0.20081115  0.13765153  0.30365738  0.13765153  0.61941955]
[ 0.60081235  0.20081178  0.13764947  0.3036416   0.13764947  0.61943533]
[ 0.60080988  0.20081002  0.13765159  0.30364525  0.13765159  0.61943167]
[ 0.60081005  0.20081001  0.13765151  0.30364359  0.13765151  0.61943334]
[ 0.60080977  0.20080978  0.13765177  0.3036439   0.13765177  0.61943302]
[ 0.60080976  0.20080976